# Generated by Django 4.2.20 on 2025-06-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_merchant_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='api.category'),
        ),
    ]
