# Generated by Django 4.2.20 on 2025-05-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
