# Generated by Django 4.2.20 on 2025-05-31 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pdfdocument_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='uploaded_at',
        ),
    ]
