# Generated by Django 4.2.20 on 2025-05-31 06:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_pdfdocument_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_document_path),
        ),
    ]
