# Generated by Django 4.2.20 on 2025-05-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merchant_transaction_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='category',
        ),
    ]
