# Generated by Django 4.2.20 on 2025-08-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_events', to='api.category'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='transaction_type',
            field=models.CharField(choices=[('expenses', 'Expenses'), ('income', 'Income')], default='income', max_length=10),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='income_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
