# Generated by Django 4.2.20 on 2025-05-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_merchant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='icon_type',
        ),
    ]
