# Generated by Django 4.2.20 on 2025-08-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_calendarevent_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(choices=[('expenses', 'Expenses'), ('income', 'Income')], default='Income', max_length=255),
        ),
    ]
