# Generated by Django 4.2.20 on 2025-05-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_merchant_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='merchants/'),
        ),
    ]
