# Generated by Django 4.2.20 on 2025-05-25 11:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_merchant_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
