# Generated by Django 4.2.20 on 2025-05-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_merchant_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
